version: '3.8'

services:
  # Redis
  redis:
    image: redis:alpine
    container_name: otp-redis
    ports:
      - "6379:6379"
    networks:
      - otp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend
  api:
    build: ./backend 
    container_name: otp-api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - FRONTEND_URL=http://localhost:3000 
      # - SMTP_HOST=${SMTP_HOST}
      # - SMTP_PORT=${SMTP_PORT}
      # - SMTP_USER=${SMTP_USER}
      # - SMTP_PASS=${SMTP_PASS}
      - EMAIL=${EMAIL}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - otp-network

  # Worker 
  worker:
    build: ./backend 
    container_name: otp-worker
    command: node workers/smsWorker.js
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - FRONTEND_URL=http://localhost:3000 
      # - SMTP_HOST=${SMTP_HOST}
      # - SMTP_PORT=${SMTP_PORT}
      # - SMTP_USER=${SMTP_USER}
      # - SMTP_PASS=${SMTP_PASS}
      - EMAIL=${EMAIL}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - otp-network

  # Frontend
  frontend:
    build: ./frontend 
    container_name: otp-frontend
    ports:
      - "3000:80" 
    depends_on:
      - api
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge